[package]
name = "multi-thread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.25.0"
rand="0.8"
num="0.4"
crossbeam="0.8"
